name: Deploy Supabase Studio to Azure Static Web Apps

on:
  push:
    branches:
      - master  # Change this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Docker Image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -f apps/studio/Dockerfile --target production -t ${{ secrets.ACR_LOGIN_SERVER }}/supabase-studio:latest .

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/supabase-studio:latest

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          skip_app_build: true  # Since we're using a Docker container
