name: Deploy Supabase Studio to Azure App Service

on:
  push:
    branches:
      - master  # Change this if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Docker Image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -f apps/studio/Dockerfile --target production -t ${{ secrets.ACR_LOGIN_SERVER }}/supabase-studio:latest .

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/supabase-studio:latest

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_WEBAPP_NAME }} --docker-custom-image-name ${{ secrets.ACR_LOGIN_SERVER }}/supabase-studio:latest

      - name: Restart Azure Web App to Apply Changes
        run: |
          az webapp restart --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_WEBAPP_NAME }}
